name: r
channels:
- r
- bioconda
dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- cairo=1.12.18=6
- configparser=3.5.0b2=py27_1
- decorator=4.0.9=py27_0
- entrypoints=0.2=py27_1
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- futures=3.0.5=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=2
- harfbuzz=0.9.39=0
- ipykernel=4.3.1=py27_0
- ipyparallel=5.0.1=py27_0
- ipython=4.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_0
- jpeg=8d=0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_2
- jupyter_client=4.2.2=py27_0
- jupyter_console=4.1.1=py27_0
- jupyter_core=4.1.0=py27_0
- libffi=3.2.1=0
- libgcc=4.8.5=1
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=1
- libxml2=2.9.3=0
- markupsafe=0.23=py27_0
- mistune=0.7.2=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- ncurses=5.9=4
- notebook=4.2.0=py27_0
- openssl=1.0.2g=0
- pango=1.39.0=0
- path.py=8.2.1=py27_0
- pcre=8.31=0
- pexpect=4.0.1=py27_0
- pickleshare=0.5=py27_0
- pip=8.1.1=py27_1
- pixman=0.32.6=0
- ptyprocess=0.5=py27_0
- pygments=2.1.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.2.1=py27_0
- r=3.2.2=0
- r-base=3.2.2=0
- r-irdisplay=0.3=r3.2.2_0a
- r-irkernel=0.5=r3.2.2_2
- r-base64enc=0.1_3=r3.2.2_0a
- r-boot=1.3_17=r3.2.2_0a
- r-class=7.3_14=r3.2.2_0a
- r-cluster=2.0.3=r3.2.2_0a
- r-codetools=0.2_14=r3.2.2_0a
- r-colorspace=1.2_6=r3.2.2_0a
- r-dichromat=2.0_0=r3.2.2_2a
- r-digest=0.6.9=r3.2.2_0
- r-evaluate=0.8=r3.2.2_0a
- r-foreign=0.8_66=r3.2.2_0a
- r-ggplot2=2.1.0=r3.2.2_0
- r-gtable=0.1.2=r3.2.2_2a
- r-irdisplay=0.3=r3.2.2_0a
- r-irkernel=0.5=r3.2.2_2
- r-jsonlite=0.9.19=r3.2.2_0
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-labeling=0.3=r3.2.2_1a
- r-lattice=0.20_33=r3.2.2_0a
- r-magrittr=1.5=r3.2.2_1a
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-mgcv=1.8_9=r3.2.2_0a
- r-munsell=0.4.2=r3.2.2_1a
- r-nlme=3.1_122=r3.2.2_0a
- r-nnet=7.3_11=r3.2.2_0a
- r-plyr=1.8.3=r3.2.2_0a
- r-rcolorbrewer=1.1_2=r3.2.2_2a
- r-rcpp=0.12.2=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-repr=0.3=r3.2.2_0a
- r-reshape2=1.4.1=r3.2.2_1a
- r-rpart=4.1_10=r3.2.2_0a
- r-rzmq=0.7.7=r3.2.2_3a
- r-scales=0.3.0=r3.2.2_0a
- r-spatial=7.3_11=r3.2.2_0a
- r-stringi=1.0_1=r3.2.2_0a
- r-stringr=1.0.0=r3.2.2_0a
- r-survival=2.38_3=r3.2.2_0a
- r-uuid=0.1_2=r3.2.2_0a
- r-glmnet=2.0_2=r3.2.2_0a
- readline=6.2=2
- setuptools=20.7.0=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_1
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- xz=5.0.5=1
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
