name: bmi
channels:
- r
- bioconda
- defaults
dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bioconda::functools32=3.2.3.2=py27_0
- bioconda::libxml2=2.9.3=0
- bioconda::r-digest=0.6.9=r3.2.2_0
- bioconda::r-jsonlite=0.9.19=r3.2.2_0
- cairo=1.12.18=6
- conda=4.1.0=py27_0
- conda-env=2.5.0=py27_0
- configparser=3.5.0b2=py27_1
- decorator=4.0.10=py27_0
- entrypoints=0.2=py27_1
- fontconfig=2.11.1=5
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py27_0
- harfbuzz=0.9.39=0
- ipykernel=4.3.1=py27_0
- ipython=4.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.2.2=py27_0
- jupyter_console=4.1.1=py27_0
- jupyter_core=4.1.0=py27_0
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libpng=1.6.17=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- markupsafe=0.23=py27_2
- mistune=0.7.2=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.2.1=py27_0
- openssl=1.0.2g=0
- pango=1.39.0=0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pcre=8.31=0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.2=py27_0
- pip=8.1.1=py27_1
- pixman=0.32.6=0
- ptyprocess=0.5.1=py27_0
- pycosat=0.6.1=py27_0
- pycrypto=2.6.1=py27_0
- pygments=2.1.3=py27_0
- pyqt=4.11.4=py27_2
- python=2.7.11=0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_1
- qt=4.8.7=2
- qtconsole=4.2.1=py27_0
- r::glib=2.43.0=2
- r::ncurses=5.9=4
- r::r=3.2.2=0
- r::r-base=3.2.2=0
- r::r-base64enc=0.1_3=r3.2.2_0a
- r::r-boot=1.3_17=r3.2.2_0a
- r::r-class=7.3_14=r3.2.2_0a
- r::r-cluster=2.0.3=r3.2.2_0a
- r::r-codetools=0.2_14=r3.2.2_0a
- r::r-evaluate=0.8=r3.2.2_0a
- r::r-foreach=1.4.3=r3.2.2_0a
- r::r-foreign=0.8_66=r3.2.2_0a
- r::r-glmnet=2.0_2=r3.2.2_0a
- r::r-irdisplay=0.3=r3.2.2_0a
- r::r-irkernel=0.5=r3.2.2_2
- r::r-iterators=1.0.8=r3.2.2_0a
- r::r-kernsmooth=2.23_15=r3.2.2_0a
- r::r-lattice=0.20_33=r3.2.2_0a
- r::r-magrittr=1.5=r3.2.2_1a
- r::r-mass=7.3_45=r3.2.2_0a
- r::r-matrix=1.2_2=r3.2.2_0a
- r::r-mgcv=1.8_9=r3.2.2_0a
- r::r-nlme=3.1_122=r3.2.2_0a
- r::r-nnet=7.3_11=r3.2.2_0a
- r::r-recommended=3.2.2=r3.2.2_0
- r::r-repr=0.3=r3.2.2_0a
- r::r-rpart=4.1_10=r3.2.2_0a
- r::r-rzmq=0.7.7=r3.2.2_3a
- r::r-spatial=7.3_11=r3.2.2_0a
- r::r-stringi=1.0_1=r3.2.2_0a
- r::r-stringr=1.0.0=r3.2.2_0a
- r::r-survival=2.38_3=r3.2.2_0a
- r::r-uuid=0.1_2=r3.2.2_0a
- r::singledispatch=3.4.0.3=py27_1
- readline=6.2=2
- requests=2.9.1=py27_0
- ruamel_yaml=0.11.7=py27_0
- setuptools=20.3=py27_0
- simplegeneric=0.8.1=py27_1
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_1
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zeromq=4.1.4=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - functools32==3.2.3.post2
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - ruamel-yaml-==VERSION
  - singledispatch==3.4.0.3
